use std::fs;
use std::os::unix::fs::PermissionsExt;
use std::path::{Path, PathBuf};

use crate::error::{AppError, Context, Result};

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ArchPackageMetadata {
    pub pkgname: String,
    pub pkgbase: String,
    pub full_version: String,
    pub version: String,
    pub release: String,
    pub epoch: Option<u64>,
    pub description: Option<String>,
    pub url: Option<String>,
    pub builddate: u64,
    pub packager: String,
    pub installed_size: u64,
    pub architecture: String,
    pub licenses: Vec<String>,
    pub depends: Vec<String>,
    pub optional_depends: Vec<String>,
    pub provides: Vec<String>,
    pub conflicts: Vec<String>,
    pub replaces: Vec<String>,
    pub backups: Vec<String>,
    pub debian_package: String,
    pub debian_version: String,
    pub debian_architecture: String,
}

impl ArchPackageMetadata {
    pub fn validate(&self) -> Result<()> {
        validate_package_name(&self.pkgname)?;
        validate_package_name(&self.pkgbase)?;
        for (name, value) in [
            ("pkgver", self.full_version.as_str()),
            ("arch", self.architecture.as_str()),
            ("packager", self.packager.as_str()),
            ("Debian package", self.debian_package.as_str()),
            ("Debian version", self.debian_version.as_str()),
            ("Debian architecture", self.debian_architecture.as_str()),
        ] {
            validate_value(name, value)?;
        }
        if self.full_version.is_empty() || self.architecture.is_empty() {
            return Err(AppError::new(
                "The package version and architecture must not be empty.",
            ));
        }
        Ok(())
    }

    pub fn render_pkginfo(&self) -> Result<String> {
        self.validate()?;
        let mut output = String::from("# Generated by debtap-rs\n");
        write_value(&mut output, "pkgname", &self.pkgname)?;
        write_value(&mut output, "pkgbase", &self.pkgbase)?;
        write_value(&mut output, "xdata", "pkgtype=pkg")?;
        write_value(
            &mut output,
            "xdata",
            &format!("debian-package={}", self.debian_package),
        )?;
        write_value(
            &mut output,
            "xdata",
            &format!("debian-version={}", self.debian_version),
        )?;
        write_value(
            &mut output,
            "xdata",
            &format!("debian-architecture={}", self.debian_architecture),
        )?;
        write_value(&mut output, "pkgver", &self.full_version)?;
        if let Some(description) = self
            .description
            .as_deref()
            .filter(|value| !value.is_empty())
        {
            write_value(&mut output, "pkgdesc", description)?;
        }
        if let Some(url) = self.url.as_deref().filter(|value| !value.is_empty()) {
            write_value(&mut output, "url", url)?;
        }
        write_value(&mut output, "builddate", &self.builddate.to_string())?;
        write_value(&mut output, "packager", &self.packager)?;
        write_value(&mut output, "size", &self.installed_size.to_string())?;
        write_value(&mut output, "arch", &self.architecture)?;
        write_values(&mut output, "license", &nonempty_or_custom(&self.licenses))?;
        write_values(&mut output, "replaces", &sorted_unique(&self.replaces))?;
        write_values(&mut output, "conflict", &sorted_unique(&self.conflicts))?;
        write_values(&mut output, "provides", &sorted_unique(&self.provides))?;
        write_values(&mut output, "backup", &sorted_unique(&self.backups))?;
        write_values(&mut output, "depend", &sorted_unique(&self.depends))?;
        write_values(
            &mut output,
            "optdepend",
            &sorted_unique(&self.optional_depends),
        )?;
        Ok(output)
    }

    pub fn output_file_name(&self) -> Result<String> {
        self.validate()?;
        Ok(format!(
            "{}-{}-{}-{}.pkg.tar.zst",
            self.pkgname, self.version, self.release, self.architecture
        ))
    }
}

pub fn write_pkginfo(root: &Path, metadata: &ArchPackageMetadata) -> Result<PathBuf> {
    let path = root.join(".PKGINFO");
    fs::write(&path, metadata.render_pkginfo()?)
        .context(format!("Cannot write {}", path.display()))?;
    fs::set_permissions(&path, fs::Permissions::from_mode(0o644))
        .context(format!("Cannot set permissions on {}", path.display()))?;
    Ok(path)
}

pub fn write_install(root: &Path, content: &str) -> Result<PathBuf> {
    let path = root.join(".INSTALL");
    fs::write(&path, content).context(format!("Cannot write {}", path.display()))?;
    fs::set_permissions(&path, fs::Permissions::from_mode(0o644))
        .context(format!("Cannot set permissions on {}", path.display()))?;
    Ok(path)
}

#[derive(Debug, Clone)]
pub struct PkgbuildSpec<'a> {
    pub metadata: &'a ArchPackageMetadata,
    pub source_deb: &'a Path,
    pub data_member: &'a str,
    pub sha256: &'a str,
}

pub fn write_pkgbuild(output_dir: &Path, spec: &PkgbuildSpec<'_>) -> Result<PathBuf> {
    spec.metadata.validate()?;
    validate_value("data member", spec.data_member)?;
    if spec.sha256.len() != 64 || !spec.sha256.bytes().all(|byte| byte.is_ascii_hexdigit()) {
        return Err(AppError::new(
            "The Debian package SHA-256 value is invalid.",
        ));
    }

    let directory = output_dir.join(format!("{}-PKGBUILD", spec.metadata.pkgname));
    if directory.exists() {
        return Err(AppError::new(format!(
            "The PKGBUILD directory already exists: {}",
            directory.display()
        )));
    }
    fs::create_dir_all(&directory).context(format!("Cannot create {}", directory.display()))?;
    let path = directory.join("PKGBUILD");
    fs::write(&path, render_pkgbuild(spec)?).context(format!("Cannot write {}", path.display()))?;
    Ok(path)
}

pub fn render_pkgbuild(spec: &PkgbuildSpec<'_>) -> Result<String> {
    spec.metadata.validate()?;
    let metadata = spec.metadata;
    let source_name = spec
        .source_deb
        .file_name()
        .and_then(|name| name.to_str())
        .ok_or_else(|| AppError::new("The Debian package file name is not valid UTF-8."))?;
    let source_path = spec
        .source_deb
        .canonicalize()
        .context(format!("Cannot resolve {}", spec.source_deb.display()))?;

    let mut output = String::from("# Generated by debtap-rs\n");
    output.push_str(&format!("pkgname={}\n", shell_quote(&metadata.pkgname)));
    output.push_str(&format!("pkgver={}\n", shell_quote(&metadata.version)));
    output.push_str(&format!("pkgrel={}\n", shell_quote(&metadata.release)));
    if let Some(epoch) = metadata.epoch {
        output.push_str(&format!("epoch={epoch}\n"));
    }
    if let Some(description) = metadata.description.as_deref() {
        output.push_str(&format!("pkgdesc={}\n", shell_quote(description)));
    }
    output.push_str(&format!("arch=({})\n", shell_quote(&metadata.architecture)));
    if let Some(url) = metadata.url.as_deref() {
        output.push_str(&format!("url={}\n", shell_quote(url)));
    }
    output.push_str(&format!(
        "license=({})\n",
        shell_array(&nonempty_or_custom(&metadata.licenses))
    ));
    output.push_str(&format!(
        "depends=({})\n",
        shell_array(&sorted_unique(&metadata.depends))
    ));
    output.push_str(&format!(
        "optdepends=({})\n",
        shell_array(&sorted_unique(&metadata.optional_depends))
    ));
    output.push_str(&format!(
        "provides=({})\nconflicts=({})\nreplaces=({})\nbackup=({})\n",
        shell_array(&sorted_unique(&metadata.provides)),
        shell_array(&sorted_unique(&metadata.conflicts)),
        shell_array(&sorted_unique(&metadata.replaces)),
        shell_array(&sorted_unique(&metadata.backups)),
    ));
    output.push_str("options=('!strip')\n");
    output.push_str(&format!(
        "source=({})\n",
        shell_quote(&format!(
            "{source_name}::file://{}",
            source_path.to_string_lossy()
        ))
    ));
    output.push_str(&format!("sha256sums=({})\n\n", shell_quote(spec.sha256)));
    output.push_str("_merge_path() {\n");
    output.push_str("    local source_path=$1 destination_path=$2 entry target\n");
    output.push_str("    [[ -e $source_path || -L $source_path ]] || return 0\n");
    output.push_str("    if [[ -d $source_path && ! -L $source_path ]]; then\n");
    output.push_str("        mkdir -p \"$destination_path\"\n");
    output.push_str("        shopt -s dotglob nullglob\n");
    output.push_str("        for entry in \"$source_path\"/*; do\n");
    output.push_str("            target=\"$destination_path/${entry##*/}\"\n");
    output.push_str("            if [[ -e $target || -L $target ]]; then\n");
    output.push_str(
        "                if [[ -d $entry && ! -L $entry && -d $target && ! -L $target ]]; then\n",
    );
    output.push_str("                    _merge_path \"$entry\" \"$target\"\n");
    output.push_str("                else\n");
    output.push_str("                    printf 'Path collision: %s\\n' \"$target\" >&2\n");
    output.push_str("                    return 1\n");
    output.push_str("                fi\n");
    output.push_str("            else\n");
    output.push_str("                mv \"$entry\" \"$target\"\n");
    output.push_str("            fi\n");
    output.push_str("        done\n");
    output.push_str("        rmdir \"$source_path\"\n");
    output.push_str("    else\n");
    output.push_str("        mkdir -p \"${destination_path%/*}\"\n");
    output.push_str("        mv \"$source_path\" \"$destination_path\"\n");
    output.push_str("    fi\n");
    output.push_str("}\n\n");
    output.push_str("package() {\n");
    output.push_str(&format!(
        "    bsdtar -xOf \"$srcdir/{source_name}\" {} | bsdtar --no-same-owner -xpf - -C \"$pkgdir\"\n",
        shell_quote(spec.data_member)
    ));
    output.push_str("    _merge_path \"$pkgdir/bin\" \"$pkgdir/usr/bin\"\n");
    output.push_str("    _merge_path \"$pkgdir/sbin\" \"$pkgdir/usr/bin\"\n");
    output.push_str("    _merge_path \"$pkgdir/usr/sbin\" \"$pkgdir/usr/bin\"\n");
    output.push_str("    _merge_path \"$pkgdir/lib\" \"$pkgdir/usr/lib\"\n");
    output.push_str("    _merge_path \"$pkgdir/lib64\" \"$pkgdir/usr/lib\"\n");
    output.push_str("    _merge_path \"$pkgdir/usr/lib64\" \"$pkgdir/usr/lib\"\n");
    output.push_str("    rm -rf \"$pkgdir/usr/share/lintian\"\n");
    output.push_str("}\n");
    Ok(output)
}

fn validate_package_name(value: &str) -> Result<()> {
    if value.is_empty()
        || value.starts_with(['-', '.'])
        || !value.bytes().all(|byte| {
            byte.is_ascii_lowercase() || byte.is_ascii_digit() || b"@._+-".contains(&byte)
        })
    {
        return Err(AppError::new(format!(
            "Invalid Arch package name: '{value}'"
        )));
    }
    Ok(())
}

fn validate_value(name: &str, value: &str) -> Result<()> {
    if value.contains(['\0', '\n', '\r']) {
        Err(AppError::new(format!(
            "The {name} value contains a forbidden control character."
        )))
    } else {
        Ok(())
    }
}

fn write_value(output: &mut String, key: &str, value: &str) -> Result<()> {
    validate_value(key, value)?;
    output.push_str(key);
    output.push_str(" = ");
    output.push_str(value);
    output.push('\n');
    Ok(())
}

fn write_values(output: &mut String, key: &str, values: &[String]) -> Result<()> {
    for value in values {
        write_value(output, key, value)?;
    }
    Ok(())
}

fn sorted_unique(values: &[String]) -> Vec<String> {
    let mut values = values
        .iter()
        .map(|value| value.trim().to_string())
        .filter(|value| !value.is_empty())
        .collect::<Vec<_>>();
    values.sort();
    values.dedup();
    values
}

fn nonempty_or_custom(values: &[String]) -> Vec<String> {
    let values = sorted_unique(values);
    if values.is_empty() {
        vec!["custom".to_string()]
    } else {
        values
    }
}

fn shell_array(values: &[String]) -> String {
    values
        .iter()
        .map(|value| shell_quote(value))
        .collect::<Vec<_>>()
        .join(" ")
}

fn shell_quote(value: &str) -> String {
    format!("'{}'", value.replace('\'', "'\\''"))
}

#[cfg(test)]
mod tests {
    use super::{ArchPackageMetadata, PkgbuildSpec, render_pkgbuild};

    fn chatgpt_metadata() -> ArchPackageMetadata {
        ArchPackageMetadata {
            pkgname: "chatgpt".to_string(),
            pkgbase: "chatgpt".to_string(),
            full_version: "26.803.81509-1".to_string(),
            version: "26.803.81509".to_string(),
            release: "1".to_string(),
            epoch: None,
            description: Some("ChatGPT by OpenAI".to_string()),
            url: Some("https://openai.com".to_string()),
            builddate: 1_700_000_000,
            packager: "Test Builder <test@example.com>".to_string(),
            installed_size: 1_312_001_200,
            architecture: "x86_64".to_string(),
            licenses: vec!["custom".to_string()],
            depends: vec!["gtk3".to_string(), "glibc".to_string()],
            optional_depends: Vec::new(),
            provides: Vec::new(),
            conflicts: Vec::new(),
            replaces: Vec::new(),
            backups: vec!["etc/apparmor.d/chatgpt".to_string()],
            debian_package: "chatgpt".to_string(),
            debian_version: "26.803.81509".to_string(),
            debian_architecture: "amd64".to_string(),
        }
    }

    #[test]
    fn renders_required_pkginfo_and_xdata() {
        let output = chatgpt_metadata().render_pkginfo().expect("PKGINFO");
        assert!(output.contains("pkgname = chatgpt\n"));
        assert!(output.contains("pkgver = 26.803.81509-1\n"));
        assert!(output.contains("size = 1312001200\n"));
        assert!(output.contains("xdata = pkgtype=pkg\n"));
        assert!(output.contains("xdata = debian-version=26.803.81509\n"));
        assert!(output.contains("depend = glibc\n"));
    }

    #[test]
    fn produces_the_standard_output_name() {
        assert_eq!(
            chatgpt_metadata().output_file_name().expect("name"),
            "chatgpt-26.803.81509-1-x86_64.pkg.tar.zst"
        );
    }

    #[test]
    fn omits_the_epoch_from_the_output_name() {
        let mut metadata = chatgpt_metadata();
        metadata.epoch = Some(2);
        metadata.full_version = "2:26.803.81509-1".to_string();
        assert_eq!(
            metadata.output_file_name().expect("name"),
            "chatgpt-26.803.81509-1-x86_64.pkg.tar.zst"
        );
    }

    #[test]
    fn rejects_newlines_in_metadata() {
        let mut metadata = chatgpt_metadata();
        metadata.packager = "bad\nvalue".to_string();
        assert!(metadata.render_pkginfo().is_err());
    }

    #[test]
    fn generated_pkgbuild_has_complete_package_function() {
        let metadata = chatgpt_metadata();
        let source = std::env::current_dir()
            .expect("directory")
            .join("Cargo.toml");
        let spec = PkgbuildSpec {
            metadata: &metadata,
            source_deb: &source,
            data_member: "data.tar.xz",
            sha256: "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef",
        };
        let output = render_pkgbuild(&spec).expect("PKGBUILD");
        assert!(output.contains("package()"));
        assert!(output.contains("bsdtar -xOf"));
        assert!(output.contains("_merge_path"));
    }
}
