use std::fs;
use std::path::Path;

use crate::error::{AppError, Result};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ScriptPolicy {
    Safe,
    None,
    Raw,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ScriptOutput {
    pub install: Option<String>,
    pub warnings: Vec<String>,
}

pub fn generate_install_script(policy: ScriptPolicy, control_dir: &Path) -> Result<ScriptOutput> {
    let scripts = MaintainerScripts::read(control_dir)?;
    let present = scripts.present_names();

    match policy {
        ScriptPolicy::None => {
            let warnings = if present.is_empty() {
                Vec::new()
            } else {
                vec![format!(
                    "The maintainer-script policy is 'none'. Omitted: {}.",
                    present.join(", ")
                )]
            };
            Ok(ScriptOutput {
                install: None,
                warnings,
            })
        }
        ScriptPolicy::Safe => Ok(generate_safe_output(&scripts)),
        ScriptPolicy::Raw => Ok(generate_raw_output(&scripts)),
    }
}

#[derive(Debug, Default)]
struct MaintainerScripts {
    preinst: Option<String>,
    postinst: Option<String>,
    prerm: Option<String>,
    postrm: Option<String>,
    triggers: Option<String>,
}

impl MaintainerScripts {
    fn read(control_dir: &Path) -> Result<Self> {
        Ok(Self {
            preinst: read_optional(control_dir, "preinst")?,
            postinst: read_optional(control_dir, "postinst")?,
            prerm: read_optional(control_dir, "prerm")?,
            postrm: read_optional(control_dir, "postrm")?,
            triggers: read_optional(control_dir, "triggers")?,
        })
    }

    fn present_names(&self) -> Vec<&'static str> {
        let mut names = self.present_script_names();
        if self.triggers.is_some() {
            names.push("triggers");
        }
        names
    }

    fn present_script_names(&self) -> Vec<&'static str> {
        let mut names = Vec::new();
        if self.preinst.is_some() {
            names.push("preinst");
        }
        if self.postinst.is_some() {
            names.push("postinst");
        }
        if self.prerm.is_some() {
            names.push("prerm");
        }
        if self.postrm.is_some() {
            names.push("postrm");
        }
        names
    }
}

fn read_optional(directory: &Path, name: &str) -> Result<Option<String>> {
    let path = directory.join(name);
    match fs::read_to_string(&path) {
        Ok(content) => Ok(Some(content)),
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => Ok(None),
        Err(error) => Err(AppError::new(format!(
            "Cannot read {}: {error}",
            path.display()
        ))),
    }
}

fn generate_safe_output(scripts: &MaintainerScripts) -> ScriptOutput {
    let present = scripts.present_names();
    if present.is_empty() {
        return ScriptOutput {
            install: None,
            warnings: Vec::new(),
        };
    }

    let mut warnings = vec![format!(
        "Safe mode omitted foreign Debian maintainer code from: {}.",
        present.join(", ")
    )];

    let combined = [
        scripts.preinst.as_deref(),
        scripts.postinst.as_deref(),
        scripts.prerm.as_deref(),
        scripts.postrm.as_deref(),
    ]
    .into_iter()
    .flatten()
    .collect::<Vec<_>>()
    .join("\n");

    if scripts.triggers.is_some() {
        warnings.push(
            "Debian dpkg triggers were not copied; Pacman transaction hooks will handle only standard cache updates."
                .to_string(),
        );
    }

    for (needle, message) in [
        ("/etc/apt", "Debian repository changes were not copied."),
        (
            "apt-get",
            "Debian package-manager commands were not copied.",
        ),
        (
            "update-alternatives",
            "Debian alternatives commands were not copied.",
        ),
        ("dpkg", "Debian package database commands were not copied."),
        (
            "apparmor_parser",
            "Debian AppArmor activation code was not copied.",
        ),
        (
            "systemctl enable",
            "Service enablement code was not copied.",
        ),
    ] {
        if combined.contains(needle) {
            warnings.push(message.to_string());
        }
    }

    warnings.push(
        "Arch package hooks will update desktop, MIME, icon, schema, linker, systemd, sysusers, and tmpfiles data."
            .to_string(),
    );

    ScriptOutput {
        install: None,
        warnings,
    }
}

fn generate_raw_output(scripts: &MaintainerScripts) -> ScriptOutput {
    let mut output = String::from(
        "# Generated by debtap-rs raw maintainer-script mode.\n\
# Review this file before installation. Debian script semantics differ from Arch.\n\n",
    );

    if let Some(body) = scripts.preinst.as_deref() {
        append_function(&mut output, "pre_install", &["install"], body);
        append_function(&mut output, "pre_upgrade", &["upgrade", "$2"], body);
    }
    if let Some(body) = scripts.postinst.as_deref() {
        append_function(&mut output, "post_install", &["configure", ""], body);
        append_function(&mut output, "post_upgrade", &["configure", "$2"], body);
    }
    if let Some(body) = scripts.prerm.as_deref() {
        append_function(&mut output, "pre_remove", &["remove"], body);
    }
    if let Some(body) = scripts.postrm.as_deref() {
        append_function(&mut output, "post_remove", &["remove"], body);
    }

    let install = if scripts.present_script_names().is_empty() {
        None
    } else {
        Some(output)
    };

    let mut warnings = vec![
        "Raw script mode can run Debian-only commands as root.".to_string(),
        "Upgrade script arguments are an approximation and require review.".to_string(),
    ];
    if scripts.triggers.is_some() {
        warnings.push("Raw mode cannot translate Debian dpkg triggers.".to_string());
    }
    ScriptOutput { install, warnings }
}

fn append_function(output: &mut String, function: &str, arguments: &[&str], body: &str) {
    output.push_str(function);
    output.push_str("() (\n");
    output.push_str("    set --");
    for argument in arguments {
        output.push(' ');
        output.push_str(&shell_word(argument));
    }
    output.push('\n');

    for line in stripped_body(body).lines() {
        output.push_str("    ");
        output.push_str(line);
        output.push('\n');
    }
    output.push_str(")\n\n");
}

fn stripped_body(body: &str) -> String {
    body.lines()
        .enumerate()
        .filter_map(|(index, line)| {
            let trimmed = line.trim();
            if (index == 0 && trimmed.starts_with("#!")) || trimmed == "set -e" {
                None
            } else {
                Some(line)
            }
        })
        .collect::<Vec<_>>()
        .join("\n")
}

fn shell_word(value: &str) -> String {
    if value.starts_with('$') {
        format!("\"{value}\"")
    } else {
        format!("'{}'", value.replace('\'', "'\\''"))
    }
}

#[cfg(test)]
mod tests {
    use std::fs;

    use super::{ScriptPolicy, generate_install_script};

    fn fixture(name: &str) -> std::path::PathBuf {
        let path =
            std::env::temp_dir().join(format!("debtap-rs-scripts-{name}-{}", std::process::id()));
        let _ = fs::remove_dir_all(&path);
        fs::create_dir_all(&path).expect("fixture directory");
        path
    }

    #[test]
    fn safe_mode_never_copies_foreign_root_code() {
        let directory = fixture("safe");
        fs::write(
            directory.join("postinst"),
            "#!/bin/sh\nset -e\napt-get update\nmkdir -p /etc/apt/sources.list.d\nupdate-alternatives --install /usr/bin/x x /opt/x 1\n",
        )
        .expect("script");
        fs::write(directory.join("triggers"), "interest update-mime\n").expect("triggers");

        let result = generate_install_script(ScriptPolicy::Safe, &directory).expect("output");
        assert!(result.install.is_none());
        let warnings = result.warnings.join(" ");
        assert!(warnings.contains("repository"));
        assert!(warnings.contains("alternatives"));
        assert!(warnings.contains("dpkg triggers"));
        fs::remove_dir_all(directory).expect("cleanup");
    }

    #[test]
    fn raw_mode_wraps_scripts_in_arch_functions() {
        let directory = fixture("raw");
        fs::write(
            directory.join("postinst"),
            "#!/bin/sh\nset -e\nprintf '%s\\n' \"$1\"\n",
        )
        .expect("script");

        let result = generate_install_script(ScriptPolicy::Raw, &directory).expect("output");
        let install = result.install.expect("raw install file");
        assert!(install.contains("post_install()"));
        assert!(install.contains("post_upgrade()"));
        assert!(!install.contains("#!/bin/sh"));
        fs::remove_dir_all(directory).expect("cleanup");
    }
}
